dbt_projects:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      password: admin
      port: 5432
      dbname: warehouse
      schema: dev
      threads: 4
      keepalives_idle: 0
