version: 2

sources:
  - name: dev
    schema: dev
    tables:
      - name: transformed_race_data
        columns:
          - name: driverId
          - name: avg_race_pos
          - name: avg_sprint_pos
          - name: avg_lap_time
          - name: points
          - name: avg_qual_pos
          - name: forename
          - name: surname

  - name: warehouse
    schema: warehouse
    tables:
      - name: predicted_race_data
        columns:
          - name: driverId
          - name: avg_race_pos
          - name: avg_sprint_pos
          - name: avg_lap_time
          - name: points
          - name: avg_qual_pos
          - name: forename
          - name: surname
          - name: driver
          - name: driver_encoded
          - name: win
          - name: win_probability
